---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Whimsical.
--- DateTime: 2021-03-16 3:26 p.m.
---

--- Original Memory Bag by MrStump
--- https://steamcommunity.com/sharedfiles/filedetails/?id=953770080

---@class MemoryListEntry
---@field public position Vector
---@field public rotation Vector
---@field public lock boolean
local MemoryListEntry={}

---@type table<string, MemoryListEntry>
local memory_list = {}

local POSTFIX = {
    SAVE = "_memory_object",
    ZONE = "_memory_zone",
    SHUFFLE = "_memory_shuffle"
}

---@type table<string, any>
local BUTTON = {
    POSITION = Vector(0, 0, 5),
    ROTATION = Vector(0, 0, 0),
    HEIGHT = 1200,
    WIDTH = 2800,
    FONT_SIZE = 800,
    COLOR = Color.Black,
    FONT_COLOR = Color.White
}

local ipairs = ipairs
local pairs = pairs

---@return string
local function get_prefix()
    return self:getDescription()
end

local function updateSave()
    local data_to_save = {["ml"]=memory_list}
    local saved_data = JSON.encode(data_to_save)
    self.script_state = saved_data
end

---@param label string
---@param action string
local function createButton(label, action)
    self:clearButtons()

    ---@type CreateClassicUIButton
    local parameters = {
        label = label,
        click_function = action,
        function_owner = self
    }

    for key, value in pairs(BUTTON) do
        parameters[key:lower()] = value
    end

    self:createButton(parameters)
end

function create_place_button() createButton("Place", "place_objects") end
local function create_recall_button() createButton("Recall", "recall_objects") end

---@param tag string
---@param lock boolean
---@return fun(object:TTSObject)
local function create_object_callback(tag, lock)
    ---@param object TTSObject
    return function (object)
        object:setLock(lock)
        if object:hasTag(tag) then object:shuffle() end
    end
end

---@param object TTSObject
local function record_objects(object)
    memory_list[object:getGUID()] = {
        position = object:getPosition(),
        rotation = object:getRotation(),
        lock = object:getLock()
    }
    self:putObject(object)
end

---@param objects TTSObject[]
local function update_objects(objects)
    for _, object in ipairs(objects) do
        record_objects(object)
    end
end

--Sends objects from bag/table to their saved position/rotation
function place_objects()
    local prefix = get_prefix()
    local shuffle_tag = prefix .. POSTFIX.SHUFFLE
    local content = self.getObjects()

    for _, item in ipairs(content) do
        local entry = memory_list[item.guid]
        if entry then
            self.takeObject {
                guid=item.guid,
                position=entry.position,
                rotation=entry.rotation,
                callback_function = create_object_callback(shuffle_tag, entry.lock)
            }
        end
    end

    broadcastToAll(self.getName().." Placed", {1,1,1})
    for _, box in pairs(Global.getTable("recallBoxes")) do
        if box ~= self then
            box.clearButtons()
        end
    end
    create_recall_button()
end

--Recalls objects to bag from table
function recall_objects()
    memory_list = {}
    local prefix = get_prefix()

    if prefix=="" then
        broadcastToAll("Error in Memory Bag: Tag prefix not set.")
        return
    end

    local save_tag = prefix .. POSTFIX.SAVE
    local zone_tag = prefix .. POSTFIX.ZONE

    local zones = getObjectsWithTag(zone_tag)
    if #zones>0 then
        for _, zone in ipairs(zones) do
            update_objects(zone:getObjects())
        end
    else
        update_objects(getObjectsWithTag(save_tag))
    end
    updateSave()
    broadcastToAll(self.getName().." Recalled", {1,1,1})
    for _, box in pairs(Global.getTable("recallBoxes")) do
        if box ~= self then
            box.call('create_place_button')
        end
    end
    create_place_button()
end

function onload(saved_data)
    if saved_data ~= "" then
        local loaded_data = JSON.decode(saved_data)
        --Set up information off of loaded_data
        memory_list = loaded_data.ml
    else
        --Set up information for if there is no saved saved data
        memory_list = {}
    end

    if self:getQuantity()==0 then
        create_recall_button()
    else
        create_place_button()
    end

    addDeckImportInput()
end

function addDeckImportInput()
    self.createInput({
        input_function = "importDeck",
        function_owner = self,
        label          = "Deck ID",
        position       = {0, 0, -6},
        rotation       = {0, 0, 0},
        width          = 3000,
        height         = 800,
        font_size      = 1000,
        color          = Color.Black,
        font_color     = Color.White,
        tooltip        = "Enter Ranger DB deck id to import",
        alignment      = 3,
        validation     = 2,
    })
end

function importDeck(_, color, input, selected)
    if input == "" or selected then
        return
    end

    local playerBoards = Global.getTable("playerBoards")
    if not playerBoards[color] then
        return
    end

    local url = "https://gapi.rangersdb.com/v1/graphql"
    local bodyData = {
        operationName = "getDeck",
        variables = {
            deckId = input,
        },
        query = "query getDeck($deckId: Int!) { deck: rangers_deck_by_pk(id: $deckId) { name awa fit foc spi meta slots user { handle } } }",
    }
    local body = JSON.encode(bodyData)
    WebRequest.custom(url, "POST", true, body, {}, function(response)
        local json = JSON.decode(response.text)
        if json.errors then
            Player[color].broadcast("Recieved error from Ranger DB website, please try again later", Color.Red)
        elseif not json.data or not json.data.deck then
            Player[color].broadcast("No Ranger DB deck found for "..input, Color.Red)
        else
            local deck = json.data.deck
            Player[color].broadcast("Importing "..deck.name.." by "..deck.user.handle, Color.White)
            local recallBoxes = Global.getTable("recallBoxes")

            local aspectBox = recallBoxes[1]
            local aspects = aspectBox.getObjects()
            local found = false
            if #aspects == 0 then
                aspects = getObjectsWithTag("Aspect")
                for _, aspect in pairs(aspects) do
                    -- Description means it was picked by a player
                    if aspect.getDescription() == "" then
                        if aspect.getVar("awareness") == deck.awa and aspect.getVar("fitness") == deck.fit and aspect.getVar("focus") == deck.foc and aspect.getVar("spirit") == deck.spi then
                            Global.call("PickAspect", {color = color, aspect = aspect})
                            found = true
                            break
                        end
                    end
                end
            else
                local aspectScript = "awareness = "..deck.awa.."\r\nfitness = "..deck.fit.."\r\nfocus = "..deck.foc.."\r\nspirit = "..deck.spi.."\r\n"
                for _, data in pairs(aspects) do
                    if data.lua_script == aspectScript then
                        local aspect = aspectBox.takeObject({guid = data.guid})
                        Global.call("PickAspect", {color = color, aspect = aspect})
                        Wait.frames(function() aspectBox.putObject(aspect) end, 3)
                        found = true
                        break
                    end
                end
            end
            if not found then
                Player[color].broadcast("Unable to find aspect with AWA "..deck.awa.." FIT "..deck.fit.." FOC "..deck.foc.." SPI "..deck.spi, Color.Red)
            end

            local roleBox = recallBoxes[4]
            local roles = roleBox.getObjects()
            found = false
            if #roles == 0 then
                roles = getObjectsWithTag("Role")
                for _, role in pairs(roles) do
                    -- Description means it was picked by a player
                    if role.getDescription() == "" then
                        if role.getVar("id") == deck.meta.role then
                            Global.call("PickRole", {color = color, role = role})
                            found = true
                            break
                        end
                    end
                end
            else
                local roleScript = "id = \""..deck.meta.role.."\"\r\n"
                for _, data in pairs(roles) do
                    if data.lua_script == roleScript then
                        local role = roleBox.takeObject({guid = data.guid})
                        Global.call("PickRole", {color = color, role = role})
                        Wait.frames(function() roleBox.putObject(role) end, 3)
                        found = true
                        break
                    end
                end
            end
            if not found then
                Player[color].broadcast("Unable to find role with id "..deck.meta.role, Color.Red)
            end

            local personalityBox = recallBoxes[2]
            local backgroundBox = recallBoxes[3]
            local specialtyBox = recallBoxes[4]
            local rewardBox = recallBoxes[5]
            local maladyBox = Global.getVar("maladiesBox")
            local function getBox(id)
                local num = tonumber(id)
                if num >= 1093 and num <= 1108 then
                    return personalityBox
                elseif num >= 1001 and num <= 1036 then
                    return backgroundBox
                elseif num >= 1037 and num <= 1092 then
                    return specialtyBox
                elseif num >= 1201 and num <= 1231 then
                    return rewardBox
                elseif num == 1240 then
                    return maladyBox
                else
                    Player[color].broadcast("Unable to find ranger card id "..id.." is out of range of any known mapping", Color.Red)
                    return nil
                end
            end

            local count = 1
            for id, quantity in pairs(deck.slots) do
                local box = getBox(id)
                if box then
                    local rangers = box.getObjects()
                    found = false
                    if #rangers == 0 then
                        rangers = getObjectsWithTag("Ranger")
                        for _, ranger in pairs(rangers) do
                            -- Description means it was picked by a player
                            if ranger.getDescription() == "" then
                                if ranger.getVar("id") == id then
                                    Global.call("PickRanger", {color = color, ranger = ranger, quantity = quantity, offset = Vector(0, 0.1 * count, 0)})
                                    count = count + 1
                                    found = true
                                    break
                                end
                            end
                        end
                    else
                        local rangerScript = "id = \""..id.."\"\r\n"
                        for _, data in pairs(rangers) do
                            if data.lua_script == rangerScript then
                                local ranger = box.takeObject({guid = data.guid})
                                Global.call("PickRanger", {color = color, ranger = ranger, quantity = quantity, offset = Vector(0, 0.1 * count, 0)})
                                Wait.frames(function() box.putObject(ranger) end, 3)
                                count = count + 1
                                found = true
                                break
                            end
                        end
                    end
                    if not found then
                        Player[color].broadcast("Unable to find ranger card with id "..id, Color.Red)
                    end
                end
            end
        end

        self.clearInputs()
        addDeckImportInput()
    end)
end
